apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-http-metrics
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: go-http-metrics
  namespace: kube-system
  labels:
    k8s-app: go-http-metrics
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    k8s-app: go-http-metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-metrics
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: go-http-metrics
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: go-http-metrics
    spec:
      serviceAccountName: go-http-metrics
      containers:
        - name: go-http-metrics
          image: quay.io/charlesakalugwu/go-http-metrics:0.0.5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: go-http-metrics
  name: go-http-metrics
  namespace: openshift-monitoring
spec:
  endpoints:
    - interval: 30s
      metrics_path: /metrics
      port: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
      - kube-system
      - openshift-infra
  selector:
    matchLabels:
      k8s-app: go-http-metrics
